repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.104.0
    hooks:
      - id: terraform_fmt
      - id: terragrunt_fmt
      - id: terraform_docs
        args:
          - --args=--lockfile=false
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_trivy
      - id: terraform_checkov
      - id: terraform_validate
      # - id: terrascan
      # - id: yamllint
